### ISSUE TITLE
Embeddium based Rendering

### ISSUE THREAD

**Issue by XVISedecim** [ItsBlackGear/Offlimits#1]
When using embeddium, placing blocks past 256 doesnt render them properly, making them clear.
![2024-05-19_13 23 37](https://github.com/ItsBlackGear/Offlimits/assets/163764140/e4e6e315-2ef5-4d21-b7ae-ae24592cce5b)

**Comment by ItsBlackGear** [comment]
noted! had the same issue with sodium so it's a simple fix, i'll try and work on it later today
