### ISSUE TITLE
Lighting Issue with Radon

### ISSUE THREAD

**Issue by XVISedecim** [ItsBlackGear/Offlimits#4]
With the Radon mod, exiting the world and going back in causes any block over 256 to go black. Reverts when a block over 256 is broken.
![2024-08-19_14 56 30](https://github.com/user-attachments/assets/34cd7b74-d6d0-4940-96b2-7b67450a61e9)

**Comment by ItsBlackGear** [comment]
Welp, i cannot said that i didn't try...

Sadly for us, both Phosphor and Radon (both on fabric and forge to be more specific) are mainly built on mixins only, sadly this prevents me to tweak their tweaks, so i think that i'll have to mark them as incompatible until i can figure out a way to properly fix them.

I'll close this issue for now, if something comes up it shall open again.
